In [2]:
import numpy as np

fpath = "/Users/luoshuai/Documents/bcmi/SEED/seed/test_data.npy"
fpath2 = "/Users/luoshuai/Documents/bcmi/SEED/seed/test_label.npy"


a = np.load(fpath)
b = np.load(fpath2)

a.shape, b.shape

((13588, 310), (13588,))

In [2]:
a[0]

array([26.24828961, 23.15422596, 21.61616599, 19.05281922, 17.54150916,
       27.0298142 , 23.01713552, 21.54442422, 18.98215664, 17.09940364,
       26.40423458, 23.0476328 , 21.54363656, 19.15847116, 17.29260907,
       25.34869133, 22.61029597, 21.30351708, 19.15062893, 17.90155318,
       25.83492164, 22.17265915, 20.98875304, 18.6711646 , 16.53198203,
       27.52370225, 26.67335481, 27.43185899, 27.28299195, 26.87985547,
       25.36319717, 22.11360251, 20.95046847, 20.63654367, 21.33987344,
       25.56229446, 21.7737903 , 20.73824057, 19.6334961 , 19.77488166,
       24.70585635, 21.33442333, 20.34584478, 18.47227009, 17.80685443,
       24.33622682, 21.24426407, 20.38882796, 18.20888423, 16.43337272,
       24.79979854, 21.31320531, 20.37938985, 18.21377492, 16.04380619,
       25.06846859, 21.18048734, 20.29029334, 18.34216825, 16.52975338,
       25.70809623, 21.66341594, 20.58104386, 18.82949176, 17.40431751,
       26.10692956, 21.93255856, 20.63543468, 18.90927915, 17.61

In [3]:
np.unique(b)

array([-1.,  0.,  1.])

In [4]:
(b == 0).sum()

4416

In [5]:
(b == -1).sum()

4480

In [6]:
(b == 1).sum()

4692

In [8]:
s = "abd.npy"
s.endswith(".nqy")

False

In [10]:
s[:-4]

'abd'

In [2]:
list(range(2, 2))

[]

In [7]:
import numpy as np

a = np.random.rand(4, 3)
a

array([[0.24880729, 0.73739625, 0.69453407],
       [0.76427207, 0.35552729, 0.50412168],
       [0.51042098, 0.2105811 , 0.67003071],
       [0.59689117, 0.90050659, 0.24685573]])

In [10]:
a[:, 1].shape

(4,)